name: CI

on: [push, pull_request]

jobs:
  testbenches:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Icarus Verilog
        run: sudo apt-get update && sudo apt-get install -y iverilog
      - name: synchronizer
        run: make MOD=synchronizer
      - name: tick_gen
        run: make MOD=tick_gen
      - name: uart_rx
        run: make MOD=uart_rx
      - name: uart_tx
        run: make MOD=uart_tx
